CREATE DATABASE IF NOT EXISTS lab4
    CHARACTER SET utf8mb4
    COLLATE utf8mb4_unicode_ci;

USE lab4;

CREATE TABLE IF NOT EXISTS topics (
    id INT AUTO_INCREMENT PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    author VARCHAR(100) NOT NULL,
    created_at DATETIME NOT NULL,
    is_pinned TINYINT(1) NOT NULL DEFAULT 0
);
